import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { AcademicCard, AcademicCardHeader } from "@/components/ui/academic-card";
import { StatusBadge } from "@/components/ui/status-badge";
import { ScoreDisplay, ScoreCircle } from "@/components/ui/score-display";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { 
  ArrowLeft, 
  Download,
  Edit3,
  Save,
  X,
  CheckCircle,
  AlertTriangle,
  Lightbulb,
  MessageSquare,
  FileText
} from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { toast } from "sonner";
import { FullEvaluationResult } from "@/lib/api/evaluation";

interface StoredEvaluation {
  examData: {
    examName: string;
    subject: string;
    totalMarks: number;
  };
  result: FullEvaluationResult;
  timestamp: string;
}

export default function EvaluationResult() {
  const navigate = useNavigate();
  const [isEditing, setIsEditing] = useState(false);
  const [evaluation, setEvaluation] = useState<StoredEvaluation | null>(null);
  const [editedScores, setEditedScores] = useState<Record<string, number>>({});
  const [editedFeedback, setEditedFeedback] = useState<Record<string, string>>({});

  useEffect(() => {
    const stored = sessionStorage.getItem("lastEvaluation");
    if (stored) {
      try {
        setEvaluation(JSON.parse(stored));
      } catch (e) {
        console.error("Failed to parse stored evaluation:", e);
        navigate("/faculty/upload");
      }
    } else {
      navigate("/faculty/upload");
    }
  }, [navigate]);

  if (!evaluation) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <FileText className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
          <p className="text-muted-foreground">Loading evaluation results...</p>
        </div>
      </div>
    );
  }

  const { examData, result } = evaluation;

  const handleSaveChanges = () => {
    setIsEditing(false);
    toast.success("Evaluation updated and approved!");
  };

  const handleDownloadReport = () => {
    // Generate a simple text report
    const report = generateTextReport();
    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${examData.examName.replace(/\s+/g, "_")}_evaluation_report.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Report downloaded successfully!");
  };

  const generateTextReport = () => {
    let report = `
================================================================================
                         EXAM EVALUATION REPORT
================================================================================

Exam: ${examData.examName}
Subject: ${examData.subject}
Date: ${new Date(evaluation.timestamp).toLocaleDateString()}

--------------------------------------------------------------------------------
                              SCORE SUMMARY
--------------------------------------------------------------------------------

Total Score: ${result.total_score} / ${result.max_score}
Percentage: ${result.percentage}%
Grade: ${result.grade}

--------------------------------------------------------------------------------
                          QUESTION-WISE BREAKDOWN
--------------------------------------------------------------------------------
`;

    result.questions.forEach((q, i) => {
      const finalScore = editedScores[q.question_id] ?? q.total_marks;
      report += `
Question ${q.question_id}
Score: ${finalScore} / ${q.max_marks}

Criteria Breakdown:
${q.criteria_breakdown.map(c => `  - ${c.criterion}: ${c.marks_awarded}/${c.max_marks} (${c.comment})`).join("\n")}

Strengths:
${q.strengths.map(s => `  ✓ ${s}`).join("\n")}

Weaknesses:
${q.weaknesses.map(w => `  ✗ ${w}`).join("\n")}

Feedback:
${editedFeedback[q.question_id] ?? q.feedback}

--------------------------------------------------------------------------------
`;
    });

    report += `
                           OVERALL ASSESSMENT
--------------------------------------------------------------------------------

Summary: ${result.summary}

Strengths:
${result.overall_strengths.map(s => `  ✓ ${s}`).join("\n")}

Areas for Improvement:
${result.overall_weaknesses.map(w => `  ✗ ${w}`).join("\n")}

Study Recommendations:
${result.study_recommendations.map(r => `  → ${r}`).join("\n")}

================================================================================
                    Generated by ExamAI Pro - AI Evaluation System
================================================================================
`;

    return report;
  };

  const getTotalScore = () => {
    return result.questions.reduce((sum, q) => {
      return sum + (editedScores[q.question_id] ?? q.total_marks);
    }, 0);
  };

  const getGradeColor = (grade: string) => {
    switch (grade) {
      case "A": return "text-score-high";
      case "B": return "text-score-high";
      case "C": return "text-score-medium";
      case "D": return "text-score-medium";
      case "F": return "text-score-low";
      default: return "text-foreground";
    }
  };

  return (
    <div className="space-y-8 animate-fade-in">
      {/* Header */}
      <div className="flex items-start justify-between flex-wrap gap-4">
        <div className="flex items-center gap-4">
          <Link to="/faculty">
            <Button variant="ghost" size="icon">
              <ArrowLeft className="w-5 h-5" />
            </Button>
          </Link>
          <div>
            <h1 className="font-heading text-2xl font-bold text-foreground">{examData.examName}</h1>
            <p className="text-muted-foreground">
              {examData.subject} • AI Evaluation Complete
            </p>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <StatusBadge status="evaluated" />
          {!isEditing ? (
            <>
              <Button variant="outline" onClick={handleDownloadReport} className="gap-2">
                <Download className="w-4 h-4" />
                Download Report
              </Button>
              <Button onClick={() => setIsEditing(true)} className="gap-2">
                <Edit3 className="w-4 h-4" />
                Edit & Approve
              </Button>
            </>
          ) : (
            <>
              <Button variant="outline" onClick={() => setIsEditing(false)} className="gap-2">
                <X className="w-4 h-4" />
                Cancel
              </Button>
              <Button onClick={handleSaveChanges} className="gap-2">
                <Save className="w-4 h-4" />
                Save & Approve
              </Button>
            </>
          )}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Score Summary */}
        <div className="lg:col-span-1 space-y-6">
          <AcademicCard>
            <AcademicCardHeader title="Score Summary" />
            <div className="flex flex-col items-center py-4">
              <ScoreCircle 
                score={getTotalScore()} 
                maxScore={result.max_score} 
                size={140} 
              />
              <div className="mt-4 text-center">
                <p className="text-2xl font-bold text-foreground">
                  {getTotalScore()} / {result.max_score}
                </p>
                <p className="text-sm text-muted-foreground mt-1">Total Score</p>
                <div className="mt-3 flex items-center justify-center gap-4">
                  <span className={`text-lg font-bold ${getGradeColor(result.grade)}`}>
                    Grade: {result.grade}
                  </span>
                  <span className="text-muted-foreground">
                    ({result.percentage}%)
                  </span>
                </div>
              </div>
              {result.total_score !== getTotalScore() && (
                <div className="mt-4 p-3 rounded-lg bg-secondary/50 text-sm">
                  <p className="text-muted-foreground">
                    AI Score: <span className="font-medium text-foreground">{result.total_score}</span>
                  </p>
                </div>
              )}
            </div>
          </AcademicCard>

          <AcademicCard>
            <AcademicCardHeader title="Exam Details" />
            <div className="space-y-3 text-sm">
              <div className="flex justify-between">
                <span className="text-muted-foreground">Exam</span>
                <span className="font-medium text-foreground">{examData.examName}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Subject</span>
                <span className="font-medium text-foreground">{examData.subject}</span>
              </div>
              <div className="flex justify-between">
                <span className="text-muted-foreground">Evaluated At</span>
                <span className="font-medium text-foreground">
                  {new Date(evaluation.timestamp).toLocaleString()}
                </span>
              </div>
            </div>
          </AcademicCard>

          <AcademicCard>
            <AcademicCardHeader title="Overall Assessment" />
            <div className="space-y-4">
              <p className="text-sm text-foreground">{result.summary}</p>
              
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <CheckCircle className="w-4 h-4 text-score-high" />
                  <span className="text-sm font-medium text-foreground">Strengths</span>
                </div>
                <ul className="space-y-1 text-sm text-muted-foreground">
                  {result.overall_strengths.map((s, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-score-high mt-1">•</span>
                      {s}
                    </li>
                  ))}
                </ul>
              </div>
              
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <AlertTriangle className="w-4 h-4 text-score-medium" />
                  <span className="text-sm font-medium text-foreground">Areas for Improvement</span>
                </div>
                <ul className="space-y-1 text-sm text-muted-foreground">
                  {result.overall_weaknesses.map((a, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-score-medium mt-1">•</span>
                      {a}
                    </li>
                  ))}
                </ul>
              </div>
              
              <div>
                <div className="flex items-center gap-2 mb-2">
                  <Lightbulb className="w-4 h-4 text-primary" />
                  <span className="text-sm font-medium text-foreground">Study Recommendations</span>
                </div>
                <ul className="space-y-1 text-sm text-muted-foreground">
                  {result.study_recommendations.map((r, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-primary mt-1">•</span>
                      {r}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </AcademicCard>
        </div>

        {/* Question-wise Evaluation */}
        <div className="lg:col-span-2 space-y-6">
          <h2 className="font-heading text-xl font-semibold text-foreground">Question-wise Evaluation</h2>
          
          {result.questions.map((question) => (
            <AcademicCard key={question.question_id}>
              <div className="flex items-start justify-between mb-4">
                <div className="flex-1">
                  <div className="flex items-center gap-3">
                    <span className="px-3 py-1 rounded-lg bg-primary/10 text-primary text-sm font-medium">
                      {question.question_id}
                    </span>
                  </div>
                </div>
                <div className="text-right">
                  {isEditing ? (
                    <div className="flex items-center gap-2">
                      <Input
                        type="number"
                        className="w-20 text-center"
                        value={editedScores[question.question_id] ?? question.total_marks}
                        onChange={(e) => setEditedScores({
                          ...editedScores,
                          [question.question_id]: Math.min(parseInt(e.target.value) || 0, question.max_marks)
                        })}
                        max={question.max_marks}
                        min={0}
                      />
                      <span className="text-muted-foreground">/ {question.max_marks}</span>
                    </div>
                  ) : (
                    <ScoreDisplay 
                      score={editedScores[question.question_id] ?? question.total_marks} 
                      maxScore={question.max_marks} 
                      size="sm"
                    />
                  )}
                </div>
              </div>

              {/* Criteria Breakdown */}
              <div className="mb-4 p-4 rounded-lg bg-secondary/30 border border-border">
                <div className="flex items-center gap-2 mb-3">
                  <ClipboardList className="w-4 h-4 text-muted-foreground" />
                  <span className="text-sm font-medium text-foreground">Marking Criteria</span>
                </div>
                <div className="space-y-2">
                  {question.criteria_breakdown.map((criterion, idx) => (
                    <div key={idx} className="flex items-start justify-between text-sm">
                      <div className="flex-1">
                        <span className="text-foreground">{criterion.criterion}</span>
                        <p className="text-xs text-muted-foreground mt-0.5">{criterion.comment}</p>
                      </div>
                      <span className={`font-medium ml-4 ${
                        criterion.marks_awarded === criterion.max_marks 
                          ? "text-score-high" 
                          : criterion.marks_awarded > 0 
                            ? "text-score-medium"
                            : "text-score-low"
                      }`}>
                        {criterion.marks_awarded}/{criterion.max_marks}
                      </span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Student Answer Excerpt */}
              {question.student_answer_excerpt && (
                <div className="mb-4 p-4 rounded-lg bg-muted/30 border border-border">
                  <div className="flex items-center gap-2 mb-2">
                    <MessageSquare className="w-4 h-4 text-muted-foreground" />
                    <span className="text-sm font-medium text-muted-foreground">Student Answer (Excerpt)</span>
                  </div>
                  <p className="text-sm text-foreground italic">"{question.student_answer_excerpt}"</p>
                </div>
              )}

              {/* Feedback */}
              <div className="space-y-3">
                <div className="flex items-start gap-3">
                  <CheckCircle className="w-4 h-4 text-score-high mt-1 flex-shrink-0" />
                  <div>
                    <span className="text-sm font-medium text-foreground">Strengths:</span>
                    <ul className="text-sm text-muted-foreground mt-1">
                      {question.strengths.map((s, i) => (
                        <li key={i}>• {s}</li>
                      ))}
                    </ul>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <AlertTriangle className="w-4 h-4 text-score-low mt-1 flex-shrink-0" />
                  <div>
                    <span className="text-sm font-medium text-foreground">Weaknesses:</span>
                    <ul className="text-sm text-muted-foreground mt-1">
                      {question.weaknesses.map((w, i) => (
                        <li key={i}>• {w}</li>
                      ))}
                    </ul>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <Lightbulb className="w-4 h-4 text-primary mt-1 flex-shrink-0" />
                  <div className="flex-1">
                    <span className="text-sm font-medium text-foreground">Feedback:</span>
                    {isEditing ? (
                      <Textarea
                        className="mt-2 text-sm"
                        value={editedFeedback[question.question_id] ?? question.feedback}
                        onChange={(e) => setEditedFeedback({
                          ...editedFeedback,
                          [question.question_id]: e.target.value
                        })}
                        rows={3}
                      />
                    ) : (
                      <p className="text-sm text-muted-foreground mt-1">
                        {editedFeedback[question.question_id] ?? question.feedback}
                      </p>
                    )}
                  </div>
                </div>
              </div>
            </AcademicCard>
          ))}
        </div>
      </div>
    </div>
  );
}

// Import this icon
import { ClipboardList } from "lucide-react";
